verant:
    resource: "@VerantBundle/Resources/config/routing.yml"
    prefix:   /verant

web_verant:
    resource: "@WebVerantBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
