faq_index:
    path:     /
    defaults: { _controller: "WebVerantBundle:Faq:index" }
    methods:  GET

faq_show:
    path:     /show/{id}
    defaults: { _controller: "WebVerantBundle:Faq:show" }
    methods:  GET

faq_new:
    path:     /new
    defaults: { _controller: "WebVerantBundle:Faq:new" }
    methods:  [GET, POST]

faq_edit:
    path:     /edit/{id}
    defaults: { _controller: "WebVerantBundle:Faq:edit" }
    methods:  [GET, POST]

faq_delete:
    path:     /delete/{id}
    defaults: { _controller: "WebVerantBundle:Faq:delete" }
    methods:  DELETE
