<?php

namespace WebVerantBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatosVerantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosVerantRepository extends EntityRepository
{
}
